### ISSUE TITLE
The submit button is distracting - grey scale it or increase transparency

### ISSUE THREAD

**Issue by joesimmons101** [alexpriceonline/StorySumo#16]
On the new request form section you currently have to customise the form. You can't just select it, as it currently is. This adds a step in the process that will not apply to people. Insert a 'select' and a 'customise' button.

**Comment by alexpriceonline** [comment]
@joesimmons101 the title seems to be a different issue from the comment. Can you clarify which it is or split them into 2 issues please. Thanks.

**Comment by alexpriceonline** [comment]
Never mind, the comment seems to be a duplicate of #15 
I'll take the title as-is.
