### ISSUE TITLE
Should the 'link' functionality drop down from the menu like it used to?

### ISSUE THREAD

**Issue by joesimmons101** [alexpriceonline/StorySumo#19]
I was a little confused by the send functionality. When trying to get a link, when i only had one form, it popped down from the top and it looked like a new screen. then when i had 2 forms it popped down and i realised it was a drop down on the same page. This was just a little confusing. suggested solutions:

- the link drops down from the individual button you press - this would be constant in all situations
- the link box is already there when you get into the page - this would stop it looking like a new page was opened when there was only 1 form

**Comment by alexpriceonline** [comment]
Nice. Yeah, I think the easiest solution is the second option. We can have the box there with some help text about selecting one of their forms. Give me a thumb if you think that is okay.

**Comment by joesimmons101** [comment]
hahaha :thumb:

**Comment by joesimmons101** [comment]
:+1:
