### ISSUE TITLE
Text for Empty Story Form view

### ISSUE THREAD

**Issue by alexpriceonline** [alexpriceonline/StorySumo#41]
We need some text for this screen. Can you write something please?

![screen shot 2016-03-07 at 18 38 06](https://cloud.githubusercontent.com/assets/15145964/13579161/cb804474-e493-11e5-9866-ee2fe064a86c.png)

**Comment by joesimmons101** [comment]
Before you collect customer feedback and stories you need to create your first story form. Click the link below to build a powerful story form to send to your customers.

**Comment by joesimmons101** [comment]
...or display on your website.
