### ISSUE TITLE
Text for on-boarding

### ISSUE THREAD

**Issue by alexpriceonline** [alexpriceonline/StorySumo#49]
We need some text for each of these sections pleaseeeee :)

![screen shot 2016-03-12 at 09 13 08](https://cloud.githubusercontent.com/assets/15145964/13722153/ca7cd022-e832-11e5-90b9-0c61631be058.png)

**Comment by joesimmons101** [comment]
Story Forms are the forms you'll send to your customers. They ask the right questions to get your customers' stories and detailed feedback. You can use a template or start from scratch and build your own.

Once your Story Form is created and customised you can quickly and easily send a link. Grab your link here then send it to your customers.

You can also embed your story form in your website to make it extra easy for your customers to share their story. Grab the code snippet here to quickly embed your Story Form.
